# Generated by Django 4.2.15 on 2024-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_delivery_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
