# Generated by Django 4.2.15 on 2024-08-22 16:32

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=market.models.product_image_upload_to),
        ),
    ]
