# Generated by Django 5.1 on 2024-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_wishlist_products_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='market.product'),
        ),
    ]
