# Generated by Django 5.1 on 2024-08-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_wishlist_products_wishlist_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
