# Generated by Django 5.1 on 2024-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_comment_content_alter_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
    ]
